[package]
name = "ocr-client"
description = "Optical Character Recognition Client that works in conjunction with OCR-Server"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.40"
either = "1.15.0"
image = "0.25.6"
pdf = {package = "pdfium-render", version = "0.8.29", features = ["thread_safe"]}
regex = "1.11.1"
reqwest = {version = "0.12.15", features = ["rustls-tls", "json", "multipart"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = "1.44.1"
url = "2.5.4"


[build-dependencies]
cc = "1.2.17"


[dev-dependencies]
tokio = {version = "*", features = ["full"]}
