[package]
name = "ocr-client"
description = "Optical Character Recognition Client that works in conjunction with OCR-Server"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.15"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.44.1"
